### ISSUE TITLE
Mus Musculus: Histone->Pluripotent Stem cells->mESC, differentiated database does not work

### ISSUE THREAD

**Issue by mark0237** [inutano/chip-atlas#19] opened 2020-06-08 21:10 UTC
Mus Musculus: Histone->Pluripotent Stem cells->mESC, differentiated database does not work. It is impossible to download nor view on the IGV. it shows an error message when trying to do it.

**Comment by shinyaoki** [comment] 2020-06-08 22:32
Hi,

Thank you for the bug report.
The error seems to be caused by the URL having comma (,), which will be fixed by the next update of ChIP-Atlas.
You can instead visualize the genomic localization of "histones" in "mESC, differentiated" as follows:

1) Launch IGV and specify mm9 as a genome assembly.
2) File > Load from URL...
3) Enter following URL:
http://dbarchive.biosciencedbc.jp/kyushu-u/mm9/assembled/His.PSC.05.AllAg.mESCs,_differentiated.bed

Shinya

**Comment by mark0237** [comment] 2020-06-16 14:48
thank you so much, it helped to view the whole set of experiments, but when
i try to view the big wig file of a certain experiment, it has the same
error.
for example this one
http://chip-atlas.org/view?id=SRX254804

how can i bypass the bug and view the big wig in these cases?

thank you


*Lic. Marcos Gabriel Francia*
*Profesor Adjunto - Universidad del Salvador*
*Becario Doctoral - CONICET*
Laboratorio de Regulación Génica en Células Madre
Departamento de Química Biológica
Facultad de Ciencias Exactas y Naturales
Universidad de Buenos Aires.
IQUIBICEN, CONICET-UBA.
Intendente Guiraldes 2160
Ciudad Universitaria, Pab. 2, 4to piso, QB-71
C1428EGA, Buenos Aires
Argentina
tel: +54-11-5285-8683
fax: +54-11-4576-3342
marcos@qb.fcen.uba.ar

**Comment by shinyaoki** [comment] 2020-06-23 12:09
Hi,

Apologies for my late reply.
Upon clicking on "View on IGV" button in SRX254804 web page, ChIP-Atlas internally produce a following URL to load corresponding bigwig on IGV:
http://localhost:60151/load?file=http://dbarchive.biosciencedbc.jp/kyushu-u/mm9/eachData/bw/SRX254804.bw&genome=mm9&name=H3K27ac%20(@%20mESCs,%20differentiated)%20SRX254804

But, the URL is invalid because it includes a comma (,). To bypass this error:
1) Launch IGV.
2) File > Load from URL
3) Enter following URL:
http://dbarchive.biosciencedbc.jp/kyushu-u/mm9/eachData/bw/SRX254804.bw <http://dbarchive.biosciencedbc.jp/kyushu-u/mm9/eachData/bw/SRX254804.bw>

This bug will be fixed by next update of ChIP-Atlas

Best,
Shinya


> 2020/06/16 23:48、mark0237 <notifications@github.com>のメール:
> 
> 
> thank you so much, it helped to view the whole set of experiments, but when
> i try to view the big wig file of a certain experiment, it has the same
> error.
> for example this one
> http://chip-atlas.org/view?id=SRX254804
> 
> how can i bypass the bug and view the big wig in these cases?
> 
> thank you
> 
> 
> *Lic. Marcos Gabriel Francia*
> *Profesor Adjunto - Universidad del Salvador*
> *Becario Doctoral - CONICET*
> Laboratorio de Regulación Génica en Células Madre
> Departamento de Química Biológica
> Facultad de Ciencias Exactas y Naturales
> Universidad de Buenos Aires.
> IQUIBICEN, CONICET-UBA.
> Intendente Guiraldes 2160
> Ciudad Universitaria, Pab. 2, 4to piso, QB-71
> C1428EGA, Buenos Aires
> Argentina
> tel: +54-11-5285-8683
> fax: +54-11-4576-3342
> marcos@qb.fcen.uba.ar
> 
> 
> El lun., 8 de jun. de 2020 a la(s) 19:32, Shinya Oki (

**Comment by inutano** [comment] 2021-03-01 07:02
I'm closing this because the last update has already fixed this, let us know if you still have any problem with this @mark0237

**Closed by inutano** 2021-03-01 07:02 UTC
